name: Flutter Test
on: [pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.27.0'

      - name: Install dependencies
        run: flutter pub get

      - name: Create .env file in assets/
        run: |
          mkdir -p assets
          echo "BASE_URL=${{ secrets.BASE_URL }}" >> assets/.env
          echo "API_KEY=${{ secrets.API_KEY }}" >> assets/.env

      - name: Check .env file
        run: cat assets/.env

      - name: Run Flutter Tests
        run: flutter test --coverage